apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-busybox-curl
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: ikulyk404/busyboxplus:curl
            resources:
              requests:
                cpu: "100m"
                memory: "100Mi"
              limits:
                cpu: "200m"
                memory: "200Mi"
            command: ["/bin/sh", "-c"]
            args:
              - curl -s http://todoapp-service.todoapp.svc.cluster.local:80/api/health;
          restartPolicy: OnFailure

  